name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "136ef9264b417cc9df3a48cd5ef9ae9895116a7f85a23e746c08aec552005021"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
