name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a70a00f94ccd51ebcfc6f6deec0bf32a238d25164a33ee7d517dd76f2a5b8e58"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
