name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8698191505cc2376ceea172ca07c161a5dbf222fd9adcd731165cd438c0a62c1"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
