name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "344da91497ef30adb10b04bb2481939408ecff3c609267fc16a9e90b2c13d77d"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
