name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "437851efe34fcbe450341debc58ffa87a24e43da66be568048934c1d9ded96d5"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
