name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ace0146dec970ddb7f3fd9cd169fca16812e61a6fd4b3590dccaf84655806ba3"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
