name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f53d0b49db2e1a7bea80c0410b32f391cadfe79807ae0e9e02dcf518cbad935a"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
