name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "521cb1e5ac0ab45645efc94ca9adc6b34f9507c2fa191ec0019018836e8cf17b"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
