name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23b6fc4772e5d2b59c5d5fdb9b2dec68a51ef309a4ed9ba8b900b3ab1cc26ecc"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
