name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.231.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02350cab478db6e8bb4d54ec3942b225c314b45dc88e0fed56b773b12bd5d924"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
