name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa70c9677afcd82074231fc551a6c6c1c2a97fc20775e33922e75f7a93ee33cf"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
