name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.232.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09f6e8ce6cd4144946c788afac4494bb55a1567d6d32fe0119a606368a7345fd"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
