name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.220.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0242ba062c9769db9c86f387ce544afcf12ae344e72be00e07ea542b9c482d8c"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
