name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.222.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7e74530ebba0ab919fd2fdcdae54ee64a352f02eb818f2fddbecfaf8804f4f6"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
