name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.219.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77c0e40773283746adb5856138fd221f4402a660e33541bd09134a5511e10cca"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
