name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00ddd8dff870bd153a13971ea0bc5272a94b77f99a9bbd5fa0ccf5768b6a575d"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
