name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.221.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d95143ba07cbfeb21076de8840add3feea522b7ff3e8a9f2cc1dacfef974c19"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
