name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b421ffaddccc154a955b7f0bee2326a1873cd56910181e909c4958016f7cbd51"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
