name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.225.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30d4e4c095511a853cc5c01441b1ab17348b4969b7b007d94df29a96d242f474"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
