name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32bf39201af7055ca5e9c544269f23bfedb5cbf06139d08f105bdd2d4a78d12b"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
