name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a048a501a0c724e7d00667bb9c47ad58c76c64bfea1aca32fcd9298439c75bb"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
