name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.224.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84daec45a68058f852d491dd15e7fccb6ac29881a96b360f709d91c8f1544687"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
