name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18e0a8ce3fce928cdcc7d2568a273432d95da7848b9a06063376977841f4d17b"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
