name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.224.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27a689dd382f4372ec780d631e1998de5b9f4b57b111d2702e9ed4ff247c1520"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
