name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.224.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41397d9514fd080f75227908c610e55f015edeab4ba8a686c7651c50cf137fd6"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
