name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.219.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d59f0bc59db2e9db953843e94fe3b9581bc61663495d78bc7c1f99f4c4154912"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
