name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.228.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09d9ee244401d8d31d1745d1707943f61c9d76e0a2e5f6f6d69ebaff4526f48e"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
