name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "023387343f7c8f9fada9fbb4f6f17e37490ee79895d0865c7a2f0576d0f5e1d0"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
