name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50532a72e14eeb1db10f4151fa8851a3304c000a6ca4e2b6dc644eaf34392544"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
