name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.220.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76faa5f8c272069ff8dfe2aed31f7682ab37b530b0734b11c0dea9e638159c8b"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
