name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2de159dfc3a89f85817b194970b16a34312bc37ea03e10d4a4d915511483cbee"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
