name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40567dad82ea8e49e3a365c08bd42634facf285dad3d06cbd9cb4c92d597b6d7"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
