name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.232.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2551a8097d52b7431da0f8b0e89298039d6b6329a8e521d51c9c63099645a1dd"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
