name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.220.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f14ecd4f17303567012b3c45701e5792404072bc7a80606a4e1344332a268f0"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
