name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b3affb78a2485ec4b6f08b1d1189bd83135aa45989db66ef73d2f0dcd39d5df"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
