name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7deb7a74f426db632ccec62107f3f990729b79caab12613437420e68cbe5226"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
