name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.231.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f23e233c82ef6602e1cb324f11aab41c5332f70755d83d880c60bebb2e7a2ae"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
