name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.224.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2331f83f17ee91deb35ec632053c5af4b0e8ddeab301ba884cc79b59ecd2f2f9"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
