name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.230.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43a701d2097721b43c302e304fcb7a4ce2ef5831de2841e8a2ff20988981df2e"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
