name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.229.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77585cabbb75f2612474167f694c298e99109e2d84619fa6777c92fb29d926b1"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
