name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.224.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b30828d36c4ef883a9211fc40653aa3ad3cd67f65a45a2cd92c91c84c6659ba"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
