name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "011d505325d531efe265fa8b7b97ee02c3917d98f326ec816cc4d0f4d75c06f7"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
