name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "358250710c28d800fce4f7d3b62193d6e65a9fdf2615e54ba36674be411105dd"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
