name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.218.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3fc1876078e34e6b42ae5ea9169e03f765016ed88995746bdc9c8d36ad77c14"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
