name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.220.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1de3597d59011a8febde94c2c5b6c7b391a17852404013d4513ec8ecedfe38af"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
